name: hw1
description: "News App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.0
  url_launcher: ^6.0.0
  json_annotation: ^4.8.1
  provider:
  intl: ^0.18.1

dev_dependencies:
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true


